/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miAPP2;

/**
 *
 * @author admin
 */
public class formularioPral extends javax.swing.JFrame {

    /**
     * Creates new form formularioPral
     */
    public formularioPral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        cboNum = new javax.swing.JComboBox<>();
        txaSalida = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cboNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cboNum, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(txaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(cboNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(txaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNumActionPerformed
       
 int num;
 String signo="",estacion="",nombre="";
 num=Integer.parseInt(cboNum.getSelectedItem().toString());
 //Los items dentro de un JComboBox son Objetos
 //para convertirlos a enteros primero se deben convertir a String
 //para obtener el item seleccionado .getSelectedItem()
 //para convertir el item (objeto) a cadena .toString()
 switch (num){
 case 1:
 signo= "Capricornio";
 estacion= "Verano";
 nombre="Enero";
 break;
 case 2:
 signo= "Acuario";
 estacion= "Verano";
 nombre="Febrero";
 break;
 case 3:
 signo= "Piscis";
 estacion= "Verano";
 nombre="Marzo";
 break;
 case 4:
 signo= "Aries";
 estacion= "Otoño";
 nombre="Abril";
 break;
 case 5:
 signo= "Tauro";
 estacion= "Otoño";
 nombre="Mayo";
 break;
 case 6:
 signo= "Geminis";
 estacion= "Otoño";
 nombre="Junio";
 break;
 case 7:
 signo= "Cancer";
 estacion= "Invierno";
 nombre="Julio";
 break;
 case 8:
 signo= "Leo";
 estacion= "Invierno";
 nombre="Agosto";
 break;
 case 9:
 signo= "Virgo";
 estacion= "Invierno";
 nombre="Setiembre";
 break;
 case 10:
 signo= "Libra";
 estacion= "Primavera";
 nombre="Octubre";
 break;
 case 11:
 signo= "Escorpio";
 estacion= "Primavera";
 nombre="Noviembre";
 break;
 case 12:
 signo= "Sagitario";
 estacion= "Primavera";
 nombre="Diciembre";
 break;
 }
 txaSalida.setText("El nombre del mes es: "+nombre +"\n");
 txaSalida.append("Corresponde el signo: "+signo+"\n");
 txaSalida.append("Estación: "+estacion);
    }



 

 
    }//GEN-LAST:event_cboNumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formularioPral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formularioPral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formularioPral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularioPral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularioPral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboNum;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField txaSalida;
    // End of variables declaration//GEN-END:variables
}
