/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miApp2;

/**
 *
 * @author admin
 */
public class formulario extends javax.swing.JFrame {

    /**
     * Creates new form formulario
     */
    public formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboNum = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaSalida = new javax.swing.JTextArea();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zodiaco");

        cboNum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cboNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNumActionPerformed(evt);
            }
        });

        txaSalida.setColumns(20);
        txaSalida.setRows(5);
        jScrollPane1.setViewportView(txaSalida);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        label1.setText("SELECCIONA UN MÚMERO Y CALCULA...\nMES, HOROSCOPO Y ESTACIÓN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(cboNum, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(cboNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        label1.getAccessibleContext().setAccessibleName("SELECCIONA UN MÚMERO Y CALCULA TU HOROSCOPO");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNumActionPerformed
       
        int num;
         String signo="",estacion="",nombre="";
         num=Integer.parseInt(cboNum.getSelectedItem().toString());
         //Los items dentro de un JComboBox son Objetos
         //para convertirlos a enteros primero se deben convertir a String
         //para obtener el item seleccionado .getSelectedItem()
         //para convertir el item (objeto) a cadena .toString()
         switch (num){
         case 1:
         signo= "Capricornio";
         estacion= "Invierno";
         nombre="Enero";
         break;
         case 2:
         signo= "Acuario";
         estacion= "Invierno";
         nombre="Febrero";
         break;
         case 3:
         signo= "Piscis";
         estacion= "Invierno";
         nombre="Marzo";
         break;
         case 4:
         signo= "Aries";
         estacion= "Primavera";
         nombre="Abril";
         break;
         case 5:
         signo= "Tauro";
         estacion= "Primavera";
         nombre="Mayo";
         break;
         case 6:
         signo= "Geminis";
         estacion= "Primavera";
         nombre="Verano";
         break;
         case 7:
         signo= "Cancer";
         estacion= "Verano";
         nombre="Julio";
         break;
         case 8:
         signo= "Leo";
         estacion= "Verano";
         nombre="Agosto";
         break;
         case 9:
         signo= "Virgo";
         estacion= "Verano";
         nombre="Setiembre";
         break;
         case 10:
         signo= "Libra";
         estacion= "Otoño";
         nombre="Octubre";
         break;
         case 11:
         signo= "Escorpio";
         estacion= "Otoño";
         nombre="Noviembre";
         break;
         case 12:
         signo= "Sagitario";
         estacion= "Otoño Invierno";
         nombre="Diciembre";
         break;
         }
txaSalida.setText("El nombre del mes es: "+nombre +"\n");
txaSalida.append("Corresponde el signo: "+signo +"\n");
txaSalida.append("Estación: "+estacion +"\n");
  
    }//GEN-LAST:event_cboNumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboNum;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JTextArea txaSalida;
    // End of variables declaration//GEN-END:variables
}
